Universe              = vanilla
executable            = runSelectionsQCD.sh
arguments             = 10000 $(ProcId)
#arguments             = 10000 23
GetEnv                = True
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
requirements 	      = (OpSysAndVer =?= "CentOS7")
+JobFlavour           = "espresso"

queue 1000
#queue 1
